### PR TITLE
+ Create new document section for RMQSignal (2.4 Auxiliary Utilities)

### PR DESCRIPTION
**Pull request by milanac030988**

### CODE REVIEW

**Review by test-fullautomation — APPROVED** [review]
Hi Cuong,
very good!
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Cuong,

please don't use `\begin{verbatim}` for code or console.

We have own styles for that:

```
\begin{robotcode}
\begin{robotlog}
\rcode{}
\rlog{}
```

**Comment by test-fullautomation** [comment]
@milanac030988 ,
Hi Cuong,
can you please correct this.
Thank you,
 Thomas

**Comment by milanac030988** [comment]
> @milanac030988 , Hi Cuong, can you please correct this. Thank you, Thomas

Hello Thomas,

I've updated by the pull-request https://github.com/test-fullautomation/robotframework-qconnect-base/pull/40

Thanks,
Cuong

**Comment by test-fullautomation** [comment]
very good!

**Pull request merged**
